title: navytuner
description: "Seongjun Hong — projects and lifestyle blog."
url: "https://navytuner.github.io"
baseurl: ""

permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

include:
  - _pages

collections_dir: ""

future: true

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
